# Generated by Django 3.0.5 on 2022-11-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveregister',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
