# Generated by Django 4.1.3 on 2022-11-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='email',
            new_name='temail',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='tname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='number',
            new_name='tnumber',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='password',
            new_name='tpassword',
        ),
    ]
